export const ErrorMsgs = {
  email: ' Invalid Email',
  password: 'Min 6 characters,1 letter,1 number,1 special character',
  mobileNumber: 'Invalid MobileNumber',
  dob: 'Invalid date of birth',
  designation: 'Invalid designation',
  dept: 'Select department',
  lane: 'Enter lane no',
  city: 'Enter city',
  country: 'select country',
  pincode: 'enter pincode',
  fullname: 'Enter user name',
  about: 'Enter about user',
  oldPassword: 'Invalid oldPassword',
  newPassword: 'Min 6 characters,1 letter,1 number,1 special character',
  confirmPassword: 'Invalid confirmPassword',
  noMatch: 'Passwords do not match',
  matchedOldMissing: 'Old Password Missing',
  color: 'Color should not be empty',
  icon: 'Icon should not be empty',
  'chapter title': 'Chapter name should not be empty',
  sections: 'Sections should have atleast one section',
  'section title': 'section title should not be empty',
  columns: 'Section should have one column',
  questiongroup: 'Atleast one questiongroup should Dropped',
  templateTitle: 'Template name should not empty',
  chaptersAdded: 'Chapters should not empty',
  specialization: 'Enter Specialization',
  notFound: 'Something Went Wrong',
  emptyQgTitle: 'Question Group name should not empty',
  noDroppedField: 'Atleast One Field should be dropped',
  noFieldSettings: 'Field Settings are empty',
  emptyFieldLabel: 'Field Label Can not be empty',
  emptyQgType: 'Question Group Type should not empty',
  noChoice: 'Atleast one choice should be selected',
  emptyChoice: 'Choice Can not be empty'
}
